// Catalogo ingredienti italiani keto/low-carb (PRD §5.1).
// Macros approssimati per 100 g. `exclusionGroups` mappa allergeni e diete:
// `lactose`, `egg`, `fish`, `nuts`, `gluten`, `pork`, `beef`, `vegan`.

export interface SeedIngredient {
  name: string;
  category:
    | 'verdura'
    | 'frutta'
    | 'carne'
    | 'pesce'
    | 'latticini'
    | 'uova'
    | 'condimenti'
    | 'panetteria'
    | 'frutta-secca'
    | 'erbe'
    | 'salumi';
  defaultUnit: 'g' | 'ml' | 'pz' | 'cucchiaio' | 'cucchiaino';
  kcalPer100g: number;
  proteinPer100g: number;
  fatPer100g: number;
  netCarbPer100g: number;
  exclusionGroups: string[];
  priceAvgEur?: number;
}

export const SEED_INGREDIENTS: SeedIngredient[] = [
  // VERDURA
  {
    name: 'Spinaci freschi',
    category: 'verdura',
    defaultUnit: 'g',
    kcalPer100g: 23,
    proteinPer100g: 2.9,
    fatPer100g: 0.4,
    netCarbPer100g: 1.4,
    exclusionGroups: [],
    priceAvgEur: 2.5,
  },
  {
    name: 'Asparagi',
    category: 'verdura',
    defaultUnit: 'g',
    kcalPer100g: 20,
    proteinPer100g: 2.2,
    fatPer100g: 0.1,
    netCarbPer100g: 2.1,
    exclusionGroups: [],
    priceAvgEur: 4.0,
  },
  {
    name: 'Zucchine',
    category: 'verdura',
    defaultUnit: 'g',
    kcalPer100g: 17,
    proteinPer100g: 1.2,
    fatPer100g: 0.3,
    netCarbPer100g: 2.1,
    exclusionGroups: [],
    priceAvgEur: 1.8,
  },
  {
    name: 'Pomodorini ciliegino',
    category: 'verdura',
    defaultUnit: 'g',
    kcalPer100g: 18,
    proteinPer100g: 0.9,
    fatPer100g: 0.2,
    netCarbPer100g: 3.5,
    exclusionGroups: [],
    priceAvgEur: 3.2,
  },
  {
    name: 'Avocado',
    category: 'frutta',
    defaultUnit: 'pz',
    kcalPer100g: 160,
    proteinPer100g: 2,
    fatPer100g: 15,
    netCarbPer100g: 1.8,
    exclusionGroups: [],
    priceAvgEur: 1.9,
  },
  {
    name: 'Insalata mista',
    category: 'verdura',
    defaultUnit: 'g',
    kcalPer100g: 15,
    proteinPer100g: 1.3,
    fatPer100g: 0.2,
    netCarbPer100g: 1.8,
    exclusionGroups: [],
    priceAvgEur: 2.2,
  },
  {
    name: 'Rucola',
    category: 'verdura',
    defaultUnit: 'g',
    kcalPer100g: 25,
    proteinPer100g: 2.6,
    fatPer100g: 0.7,
    netCarbPer100g: 2.0,
    exclusionGroups: [],
    priceAvgEur: 2.8,
  },
  {
    name: 'Cavolfiore',
    category: 'verdura',
    defaultUnit: 'g',
    kcalPer100g: 25,
    proteinPer100g: 1.9,
    fatPer100g: 0.3,
    netCarbPer100g: 3.0,
    exclusionGroups: [],
    priceAvgEur: 1.5,
  },
  {
    name: 'Cetrioli',
    category: 'verdura',
    defaultUnit: 'g',
    kcalPer100g: 16,
    proteinPer100g: 0.7,
    fatPer100g: 0.1,
    netCarbPer100g: 3.1,
    exclusionGroups: [],
    priceAvgEur: 1.6,
  },
  {
    name: 'Carote',
    category: 'verdura',
    defaultUnit: 'g',
    kcalPer100g: 41,
    proteinPer100g: 0.9,
    fatPer100g: 0.2,
    netCarbPer100g: 6.8,
    exclusionGroups: [],
    priceAvgEur: 1.2,
  },
  // CARNE
  {
    name: 'Petto di pollo',
    category: 'carne',
    defaultUnit: 'g',
    kcalPer100g: 165,
    proteinPer100g: 31,
    fatPer100g: 3.6,
    netCarbPer100g: 0,
    exclusionGroups: [],
    priceAvgEur: 9.5,
  },
  {
    name: 'Tagliata di manzo',
    category: 'carne',
    defaultUnit: 'g',
    kcalPer100g: 250,
    proteinPer100g: 26,
    fatPer100g: 17,
    netCarbPer100g: 0,
    exclusionGroups: ['beef'],
    priceAvgEur: 22.0,
  },
  {
    name: 'Pancetta affumicata',
    category: 'salumi',
    defaultUnit: 'g',
    kcalPer100g: 540,
    proteinPer100g: 12,
    fatPer100g: 53,
    netCarbPer100g: 1,
    exclusionGroups: ['pork'],
    priceAvgEur: 18.0,
  },
  // PESCE
  {
    name: 'Filetto di salmone',
    category: 'pesce',
    defaultUnit: 'g',
    kcalPer100g: 208,
    proteinPer100g: 20,
    fatPer100g: 13,
    netCarbPer100g: 0,
    exclusionGroups: ['fish'],
    priceAvgEur: 22.0,
  },
  {
    name: 'Branzino',
    category: 'pesce',
    defaultUnit: 'pz',
    kcalPer100g: 124,
    proteinPer100g: 24,
    fatPer100g: 2.5,
    netCarbPer100g: 0,
    exclusionGroups: ['fish'],
    priceAvgEur: 18.0,
  },
  {
    name: "Tonno sott'olio",
    category: 'pesce',
    defaultUnit: 'g',
    kcalPer100g: 200,
    proteinPer100g: 25,
    fatPer100g: 11,
    netCarbPer100g: 0,
    exclusionGroups: ['fish'],
    priceAvgEur: 12.0,
  },
  // LATTICINI
  {
    name: 'Parmigiano Reggiano',
    category: 'latticini',
    defaultUnit: 'g',
    kcalPer100g: 392,
    proteinPer100g: 36,
    fatPer100g: 28,
    netCarbPer100g: 0,
    exclusionGroups: ['lactose'],
    priceAvgEur: 24.0,
  },
  {
    name: 'Yogurt greco intero',
    category: 'latticini',
    defaultUnit: 'g',
    kcalPer100g: 95,
    proteinPer100g: 9,
    fatPer100g: 5,
    netCarbPer100g: 3.6,
    exclusionGroups: ['lactose'],
    priceAvgEur: 6.0,
  },
  {
    name: 'Ricotta vaccina',
    category: 'latticini',
    defaultUnit: 'g',
    kcalPer100g: 174,
    proteinPer100g: 11,
    fatPer100g: 13,
    netCarbPer100g: 3.0,
    exclusionGroups: ['lactose'],
    priceAvgEur: 5.5,
  },
  {
    name: 'Gorgonzola dolce DOP',
    category: 'latticini',
    defaultUnit: 'g',
    kcalPer100g: 350,
    proteinPer100g: 19,
    fatPer100g: 30,
    netCarbPer100g: 0,
    exclusionGroups: ['lactose'],
    priceAvgEur: 18.0,
  },
  {
    name: 'Burro',
    category: 'latticini',
    defaultUnit: 'g',
    kcalPer100g: 720,
    proteinPer100g: 0.9,
    fatPer100g: 81,
    netCarbPer100g: 0.1,
    exclusionGroups: ['lactose'],
    priceAvgEur: 9.0,
  },
  {
    name: 'Grana Padano',
    category: 'latticini',
    defaultUnit: 'g',
    kcalPer100g: 384,
    proteinPer100g: 33,
    fatPer100g: 28,
    netCarbPer100g: 0,
    exclusionGroups: ['lactose'],
    priceAvgEur: 18.0,
  },
  // UOVA
  {
    name: 'Uova',
    category: 'uova',
    defaultUnit: 'pz',
    kcalPer100g: 143,
    proteinPer100g: 13,
    fatPer100g: 10,
    netCarbPer100g: 0.7,
    exclusionGroups: ['egg'],
    priceAvgEur: 4.5,
  },
  // CONDIMENTI
  {
    name: 'Olio extravergine di oliva',
    category: 'condimenti',
    defaultUnit: 'cucchiaio',
    kcalPer100g: 884,
    proteinPer100g: 0,
    fatPer100g: 100,
    netCarbPer100g: 0,
    exclusionGroups: [],
    priceAvgEur: 12.0,
  },
  {
    name: 'Olive nere',
    category: 'condimenti',
    defaultUnit: 'g',
    kcalPer100g: 115,
    proteinPer100g: 0.8,
    fatPer100g: 11,
    netCarbPer100g: 3,
    exclusionGroups: [],
    priceAvgEur: 8.0,
  },
  {
    name: 'Olive verdi',
    category: 'condimenti',
    defaultUnit: 'g',
    kcalPer100g: 145,
    proteinPer100g: 1,
    fatPer100g: 15,
    netCarbPer100g: 1.5,
    exclusionGroups: [],
    priceAvgEur: 8.0,
  },
  {
    name: 'Capperi sotto sale',
    category: 'condimenti',
    defaultUnit: 'cucchiaio',
    kcalPer100g: 23,
    proteinPer100g: 2.4,
    fatPer100g: 0.9,
    netCarbPer100g: 1.7,
    exclusionGroups: [],
    priceAvgEur: 6.0,
  },
  {
    name: 'Limone',
    category: 'frutta',
    defaultUnit: 'pz',
    kcalPer100g: 29,
    proteinPer100g: 1.1,
    fatPer100g: 0.3,
    netCarbPer100g: 6.5,
    exclusionGroups: [],
    priceAvgEur: 0.6,
  },
  // FRUTTA SECCA
  {
    name: 'Mandorle',
    category: 'frutta-secca',
    defaultUnit: 'g',
    kcalPer100g: 579,
    proteinPer100g: 21,
    fatPer100g: 50,
    netCarbPer100g: 9,
    exclusionGroups: ['nuts'],
    priceAvgEur: 18.0,
  },
  {
    name: 'Noci',
    category: 'frutta-secca',
    defaultUnit: 'g',
    kcalPer100g: 654,
    proteinPer100g: 15,
    fatPer100g: 65,
    netCarbPer100g: 7,
    exclusionGroups: ['nuts'],
    priceAvgEur: 22.0,
  },
  // PANETTERIA
  {
    name: 'Pane proteico di mandorle',
    category: 'panetteria',
    defaultUnit: 'g',
    kcalPer100g: 280,
    proteinPer100g: 20,
    fatPer100g: 18,
    netCarbPer100g: 6,
    exclusionGroups: ['nuts'],
    priceAvgEur: 14.0,
  },
  // ERBE
  {
    name: 'Basilico fresco',
    category: 'erbe',
    defaultUnit: 'g',
    kcalPer100g: 23,
    proteinPer100g: 3.2,
    fatPer100g: 0.6,
    netCarbPer100g: 1.0,
    exclusionGroups: [],
    priceAvgEur: 2.0,
  },
  {
    name: 'Cannella in polvere',
    category: 'erbe',
    defaultUnit: 'cucchiaino',
    kcalPer100g: 247,
    proteinPer100g: 4,
    fatPer100g: 1.2,
    netCarbPer100g: 27,
    exclusionGroups: [],
    priceAvgEur: 5.0,
  },
];
